#!/usr/bin/env python3
"""Compose per-role image-generation prompts.

Reads the shared style block from prompts/_base.md and each role's subject
description from prompts/subjects/<role>.md, then writes a self-contained,
copy-paste-ready prompt to prompts/out/<role>.txt.

The role list and file names come from avatars.json, so adding an avatar means
adding an entry there plus a subjects/<role>.md file.

Usage:
    python3 scripts/build_prompts.py           # write prompts/out/*.txt
    python3 scripts/build_prompts.py --check   # verify out/ matches sources
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "prompts" / "_base.md"
SUBJECTS = ROOT / "prompts" / "subjects"
OUT = ROOT / "prompts" / "out"
CATALOG = ROOT / "avatars.json"

BANNER = "# Generated by scripts/build_prompts.py — edit the sources, not this file."


def section(text: str, name: str, source: Path) -> str:
    """Return the body of a `## NAME` section, up to the next `## ` heading."""
    match = re.search(
        rf"^##[ \t]+{re.escape(name)}[ \t]*$\n(.*?)(?=^##[ \t]|\Z)",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        sys.exit(f"error: {source} is missing a '## {name}' section")
    body = match.group(1).strip()
    if not body:
        sys.exit(f"error: the '## {name}' section in {source} is empty")
    return body


def render(role: str, title: str, style: str, negative: str) -> str:
    subject_path = SUBJECTS / f"{role}.md"
    if not subject_path.is_file():
        sys.exit(f"error: no subject description at {subject_path}")
    subject = section(subject_path.read_text(encoding="utf-8"), "SUBJECT", subject_path)
    return (
        f"{BANNER}\n"
        f"# role: {role} ({title})\n\n"
        f"=== PROMPT ===\n\n"
        f"{subject}\n\n"
        f"{style}\n\n"
        f"=== NEGATIVE PROMPT ===\n\n"
        f"{negative}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if prompts/out/ is stale instead of rewriting it",
    )
    args = parser.parse_args()

    base = BASE.read_text(encoding="utf-8")
    style = section(base, "STYLE", BASE)
    negative = " ".join(section(base, "NEGATIVE", BASE).split())

    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    avatars = catalog["avatars"]

    OUT.mkdir(parents=True, exist_ok=True)
    stale = []
    for avatar in avatars:
        role = avatar["role"]
        content = render(role, avatar["title_en"], style, negative)
        target = OUT / f"{role}.txt"
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == content:
            continue
        if args.check:
            stale.append(target.relative_to(ROOT))
        else:
            target.write_text(content, encoding="utf-8")
            print(f"wrote {target.relative_to(ROOT)}")

    expected = {f"{a['role']}.txt" for a in avatars}
    for orphan in sorted(p for p in OUT.glob("*.txt") if p.name not in expected):
        if args.check:
            stale.append(orphan.relative_to(ROOT))
        else:
            orphan.unlink()
            print(f"removed {orphan.relative_to(ROOT)}")

    if args.check:
        if stale:
            print("stale prompt output — run: python3 scripts/build_prompts.py")
            for path in stale:
                print(f"  {path}")
            return 1
        print(f"prompts/out/ is up to date ({len(avatars)} roles)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
